        <table>
            <tr>
                <td width="50%" id="company_info">
                    <h4>Company Info</h4>
                    <p>
                        <?php echo join("<br />", $info); ?>
                    </p>
                </td>
                <td>
                    <div id="credit_card_box">
                        <h4>Credit Card Info</h4>
                        <table>
                            <tr>
                                <td>
                                    <label>Name on Card</label><br />
                                    <input type="text" name="name" />
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    <label>Card Number</label><br />
                                    <input type="text" name="number" />
                                </td>
                                <td>
                                    <label>CSV</label><br />
                                    <input size="4" type="text" name="csv" />
                                </td>
                                <td>
                                    <label>Expiration</label><br />
                                    <select name="month">
                                        <option></option>
                                        <option></option>
                                        <option></option>
                                    </select>
                                    <select name="year">
                                        <option></option>
                                        <option></option>
                                        <option></option>
                                    </select>
                                </td>
                            </tr>
                        </table>
                    </div>
                </td>
            </tr>
        </table>
        <div class="gray_line"></div>
        <table width="100%">
            <tbody id="billing_totals">
                <!-- Generated by UI -->
                <!-- See super.php div#snippets div#billing_detail_row -->
            </tbody>
        </table>
        <div class="gray_line"></div>
        <table width="100%">
            <tr>
                <td style="padding:10px 0px 10px 10px;" align="left">ITEM TOTAL</td>
                <td align="right" id="item_total">{item_total}</td>
            </tr>
        </table>