            <?php if(count($this->cart->contents()) == 0): ?>
            <div class="cart_row">
                You have no items in your cart.
            </div>
            <?php endif; ?>
            <?php foreach($this->cart->contents() as $item): ?>
            <?php // TODO Add column headers ?>
            <div class="cart_row" id="<?php echo $item['id']; ?>">
                <div style="float:left; width:300px; padding-left:12px;">
                    <div id="item_details">
                        <?php echo $item['name']; ?>
                    </div>
                </div>
                <div style="float:left; width:300px;">
                    <div id="item_status">
                        <?php //TODO echo $item['status']; ?>
                        <?php echo $spaces[0] . " Spaces Available"; ?>
                    </div>
                </div>
                <div style="float:left; width:150px;">
                    <?php if($display == 'single'): ?>
                    <div id="item_price">
                        <?php echo '$'.$item['price']; ?>
                    </div>
                    <?php else: ?>
                    <div id="attendees">
                        <!-- Generated by UI -->
                    </div>
                    <?php endif; ?>
                </div>
                <div style="float:right; width:80px;padding-right:12px;">
                    <a class="item_remove" style="float:right;" href="" id="<?php echo $item['rowid']; ?>"></a>
                    <a class="item_edit" style="float:right;padding-right:15px;display:none;" href="" ></a>
                </div>
                <div class="clear"></div>
                <div class="gray_line" style="margin-top:20px;"></div>
            </div>
            
            <?php endforeach; ?>