            <?php foreach($this->cart->contents() as $item): ?>
            <div class="cart_row" id="<?php echo $item['id']; ?>">
                <table>
                    <tr>
                        <td style="width:30%">
                            <div id="item_details">
                                <?php echo $item['name']; ?>
                            </div>
                        </td>
                        <td style="width:30%">
                            <div id="item_status">
                                <?php //TODO echo $item['status']: ?>
                                <?php echo $spaces[0] . " Spaces Available"; ?>
                            </div>
                        </td>
                        <td style="width:30%">
                            <div id="attendees">
                                <!-- Generated by UI -->
                            </div>
                        </td>
                        <td style="width:10%;">
                            <div class="item_remove" id="<?php echo $item['rowid']; ?>">
                                Remove
                            </div>
                        </td>
                    </tr>
                </table>
            </div>
            <?php endforeach; ?>