<?php
// Some mock data
$profiles = array (
    array('id' => 1, 'name' => 'A'),
    array('id' => 2, 'name' => 'B'),
    array('id' => 3, 'name' => 'C'),
    array('id' => 4, 'name' => 'D'),
    array('id' => 5, 'name' => 'E'),
    array('id' => 6, 'name' => 'F')
);

echo '<script type="text/javascript">var profiles = JSON.parse(\'' . json_encode($profiles) . '\')</script>';
?>

    <div id="content_main_inner">
        <h1 class="page_title"><?php echo $title; ?></h1>
        <div class="gray_line"></div>
        <div id="super_cart_list">
            <?php foreach($this->cart->contents() as $item): ?>
            <div id="<?php echo $item['id']; ?>">
                <table>
                    <tr>
                        <td style="width:75%">
                            <div id="item_details">
                                <?php echo $item['name']; ?>
                            </div>
                        </td>
                        <td style="width:25%">
                            <div id="attendees">
                                <!-- Generated by UI -->
                            </div>
                        </td>
                    </tr>
                </table>
            </div>
            <?php endforeach; ?>
        </div>
        <div class="gray_line"></div>
        <div id="add_new_profile" style="float:left;margin:10px 0;">Add New Profile +</div>
        <div id="super_continue" style="float:right;margin:20px 0;width:100px;height:40px;line-height:40px;font-size:16px;background:#ccc;color:#fff;text-align:center;">Continue</div>
        <div class="clear"></div>
    </div> <!-- #content_main_inner -->