<div class="hide" id="search_box">
    <!-- header bar -->
    <div id="search_header">
        <div class="title">Search Programs</div>
        <div class="close" id="search_close"><img src="/resources/images/button_remove.png" /></div>
    </div>
    <div id="search_body">
        <label>Search by Title:</label>
        <input type='text' id="search_title"/>
        <label>Search by Type:</label>
        <select id="search_type" >
            <option value="" selected="selected">All</option>
            <!-- Generated by UI -->
        </select>
    </div>
</div>